name: CD Pipeline

on:
    workflow_run:
      workflows: [CI Pipeline]
      types:
        - completed

jobs:
    Deploy:
        runs-on:
            group: Default  
        steps:
          - name: Pull Docker image
            run: sudo docker pull nicolaspineda255/digital-photography-frontend:latest
          - name: Delete Old docker container
            run: sudo docker rm -f digital-photography-frontend-container || true
          - name: Run Docker Container
            run: sudo docker run -d -p 5173:5173 --name digital-photography-frontend-container nicolaspineda255/digital-photography-frontend
